stages:
    - build

build:
    stage: build
    image: gitlab-registry.cern.ch/agonzale/cc7-atlassian
    script:
        - atlas-mvn package
    artifacts:
        paths:
            - target/*.jar

